---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
  name: Stock
  labels:
    app: stock
    app: Stock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
      app: Stock
  template:
    metadata:
      labels:
        app: stock
        app: Stock
    spec:
      containers:
        - name: stock
          image: username/stock:latest
        - name: Stock
          image: username/Stock:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  name: Reservation
  labels:
    app: reservation
    app: Reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
      app: Reservation
  template:
    metadata:
      labels:
        app: reservation
        app: Reservation
    spec:
      containers:
        - name: reservation
          image: username/reservation:latest
        - name: Reservation
          image: username/Reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  name: Payment
  labels:
    app: payment
    app: Payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      app: Payment
  template:
    metadata:
      labels:
        app: payment
        app: Payment
    spec:
      containers:
        - name: payment
          image: username/payment:latest
        - name: Payment
          image: username/Payment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  name: Delivery
  labels:
    app: delivery
    app: Delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
      app: Delivery
  template:
    metadata:
      labels:
        app: delivery
        app: Delivery
    spec:
      containers:
        - name: delivery
          image: username/delivery:latest
        - name: Delivery
          image: username/Delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myPage
  name: MyPage
  labels:
    app: myPage
    app: MyPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myPage
      app: MyPage
  template:
    metadata:
      labels:
        app: myPage
        app: MyPage
    spec:
      containers:
        - name: myPage
          image: username/myPage:latest
        - name: MyPage
          image: username/MyPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: stock
  name: Stock
  labels:
    app: stock
    app: Stock
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: stock
    app: Stock


---


apiVersion: v1
kind: Service
metadata:
  name: reservation
  name: Reservation
  labels:
    app: reservation
    app: Reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation
    app: Reservation


---


apiVersion: v1
kind: Service
metadata:
  name: payment
  name: Payment
  labels:
    app: payment
    app: Payment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: payment
    app: Payment


---


apiVersion: v1
kind: Service
metadata:
  name: delivery
  name: Delivery
  labels:
    app: delivery
    app: Delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: delivery
    app: Delivery


---


apiVersion: v1
kind: Service
metadata:
  name: myPage
  name: MyPage
  labels:
    app: myPage
    app: MyPage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: myPage
    app: MyPage

