apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: skccacr.azurecr.io/reservation:latest
          ports:
            - containerPort: 8080
# ConfigMap TEST            
          env:
            - name: G_STORE
              valueFrom:
                configMapKeyRef:
                  name: g-store
                  key: store  
# Readiness Probe TEST             
          #readinessProbe:
          #  httpGet:
          #    path: '/actuator/health'
          #    port: 8080
          #  initialDelaySeconds: 10
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 10
# Liveness Probe TEST           
          #livenessProbe:
          #  httpGet:
          #    path: '/actuator/health_test'
          #    port: 8090
          #  initialDelaySeconds: 120
          #  timeoutSeconds: 2
          #  periodSeconds: 5
          #  failureThreshold: 5
# HPA TEST
          #resources:
          #  requests:
          #    memory: "64Mi"
          #    cpu: "250m"
          #  limits:
          #    memory: "500Mi"
          #    cpu: "500m"          